name: Docker Installer Download

on:
  workflow_dispatch: # 表示该workflow可以通过手动触发。在GitHub仓库中，你可以看到一个"Run workflow"按钮，点击后可以手动运行这个workflow
  #  schedule: # 表示该workflow可以通过定时任务触发。在这个例子中，定时任务的时间表达式为00 23 * * *，表示每天的23点0分执行一次
  #    - cron: '00 23 * * *'
  push:
    tags:
      - "check*"
permissions:
  contents: write
jobs:
  download_installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: show env
        run: |
          echo ${{ github.workspace }}
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          echo ${{ github.repository }}
          echo ${{ github.event_name }}
          echo ${{ github.event }}
          echo ${{ env.ENV_VARIABLE }}
          echo ${{ secrets.SECRET_NAME }}
          echo ${{ steps.STEP_ID.outputs.OUTPUT_NAME }}
          echo ${{ runner.os }}
          echo ${{ runner.temp }}
          echo ${{ runner.tool_cache }}
          echo ${{ matrix.environment }}
          echo ${{ matrix.include }}
          echo ${{ needs.JOB_ID.outputs.OUTPUT_NAME }}
          echo ${{ inputs.INPUT_ID }}
          echo ${{ job.status }}
          echo ${{ job.container }}
          echo ${{ strategy.fail-fast }}
          echo ${{ strategy.job-index }}
          echo ${{ strategy.job-total: }}
          echo ${{ strategy.max-parallel }}