name: Upload Docker Image To Mega

on:
  workflow_dispatch:
  push:
    #    branches:
    #      - 'master'
    tags:
      - 'upload*'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Version
        run: |
          cat /etc/apt/sources.list
          ls -ahtl /etc/apt/sources.list.d
      - name: Install Mega
        run: |
          wget https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megacmd-xUbuntu_22.04_amd64.deb && sudo apt install "$PWD/megacmd-xUbuntu_22.04_amd64.deb"
      - name: Login Mega
        run: |
          mega-login ${{ secrets.MEGA_EMAIL }} ${{ secrets.MEGA_PASSWORD }}
          mega-whoami
      - name: Docker Pull
        run: |
          docker pull zhangyiming748/stand:latest
      - name: Docker Save
        run: |
          docker save zhangyiming748/stand:latest | xz -9e > stand.tar.xz
      - name: Upload xz
        run: |
          mega-put stand.tar.xz /docker/stand.tar.xz