name: Docker Imager Download
on:
  workflow_dispatch:
  push:
    tags:
      #- "alpine-3.20.1"
      - "*-*"
permissions:
  contents: write
jobs:
  download_installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get ref.tags
        run: echo "The current tag is ${{ github.ref }}"
      - name: Get event.tags
        run: echo "The current tag is ${{ github.event.ref }}"
      - name: Get purge tag nam
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##g')
          echo "The tag name is $TAG_NAME"
      - name: Get image and version
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##g')
          NAME_PART=${TAG_NAME%%-*}
          VERSION_PART=${TAG_NAME#*-}
          echo "Alpine part: $NAME_PART"
          echo "Version part: $VERSION_PART"
          echo "docker save -o $NAME_PART-$VERSION_PART.tar $NAME_PART:$VERSION_PART"
#      - name: Download installers
#        run: |
#          docker pull
#          docker save -o
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            linux.sh
#            docker_desktop_installer_windows_x86_64.exe
#            docker_desktop_installer_mac_arm64.dmg
#            docker_desktop_installer_mac_x84_64.dmg
#            docker_desktop_installer_linux_debian_x84_64.dmg
#            docker_desktop_installer_linux_fedora_x84_64.dmg
#          tag_name: latest_release
#      - name: ls
#        run: ls ${{ github.workspace }}
#      - name: Upload Build Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: Docker installers
#          path: ${{ github.workspace }}