name: Docker Imager Download
on:
  workflow_dispatch:
  push:
    tags:
      #- "alpine-3.20.1"
      - "*-*"
permissions:
  contents: write
jobs:
  download_installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get ref.tags
        run: echo "The current tag is ${{ github.ref }}"
      - name: Get event.tags
        run: echo "The current tag is ${{ github.event.ref }}"
      - name: Get purge tag nam
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##g')
          echo "The tag name is $TAG_NAME"
      - name: Get image and version
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##g')
          NAME_PART=${TAG_NAME%%-*}
          VERSION_PART=${TAG_NAME#*-}
          echo "Alpine part: $NAME_PART"
          echo "Version part: $VERSION_PART"
          FILE_NAME=$NAME_PART-$VERSION_PART.tar
          IMAGE_NAME=$NAME_PART:$VERSION_PART
          docker pull $IMAGE_NAME
          docker save -o $FILE_NAME $IMAGE_NAME
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar
          tag_name: "last_release"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Docker Image tar
          path: ${{ github.workspace }}/*.tar