name: Linux Kernel Download

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  download_kernel:
    runs-on: ubuntu-latest
    steps:
#      - name: get version
#        run: |
#          sudo apt install neofetch
#          neofetch
#          ubuntu22.04
      - name: Get MegaCMD
        run: |
          wget https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megacmd-xUbuntu_22.04_amd64.deb 
          sudo apt install "$PWD/megacmd-xUbuntu_22.04_amd64.deb"
      - name: mega login
        run:  mega-login ${{ secrets.MEGA_EMAIL }} ${{ secrets.MEGA_PASSWORD }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Time
        run: |
          CURRENT_TIME=$(date)
          echo "Current time is: $CURRENT_TIME"
      - name: Get Kernel
        run: |
          git clone https://github.com/torvalds/linux.git
      - name: tar
        run: tar cvf linux.tar linux
      - name: xz
        run: xz -9ev linux.tar
      - name: ls
        run: |
          ls -alh
      - name: mega
        run: |
          mega-put linux.tar.xz /kernel
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux kernel
          path: |
            linux.tar.xz
