name: Linux Kernel Download

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  download_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: get version
        run: |
          sudo apt install neofetch
          neofetch
          xz
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Time
        run: |
          CURRENT_TIME=$(date)
          echo "Current time is: $CURRENT_TIME"
      - name: Get Kernel
        run: |
          git clone https://github.com/torvalds/linux.git 
      - name: tar
        run: tar cvf linux.tar linux
      - name: xz
        run: xz -9ev linux.tar
      - name: ls
        run: |
          ls -alh
      - name: mega
        run: |
          apt install -y megacmd
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Docker installers
          path: |
            linux.tar.xz
