name: Linux Kernel Download

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  download_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Time
        run: |
          echo "Workflow triggered at: ${{ github.event.created_at }}"
      - name: Get Kernel
        run: |
          git clone https://github.com/torvalds/linux.git ${{ github.event.workflow_run.head_commit.timestamp }}
          tar cvf linux.tar linux
          ls -alh linux.tar
          xz -9k linux.tar
      - name: ls
        run: |
          ls -alh
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       linux.tar.xz
      #     tag_name: latest_release
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Docker installers
          path: |
            linux.tar.xz
